---
title: "Pr_2"
author: "Blinkova_A_A"
date: "2024-04-27"
output: html_notebook
---

```{r echo=FALSE, message = FALSE, warning=FALSE}
setwd("D:\\Прога\\ЦК анализ мед данных\\Основы программирования на R")
library(dplyr)
library(ggplot2)
library(readxl)

```
# Подгрузка данных

```{r echo=FALSE, message = FALSE, warning=FALSE}
dt <- read_excel("D:/Прога/ЦК анализ мед данных/Основы программирования на R/data_pr_2.xlsx")
colnames(dt)
head(dt)
unique(dt$Продукт)
```
# Предобработка
## Удаление нулевых строк 
```{r echo=FALSE, message = FALSE, warning=FALSE}
data2 <- na.omit(dt)
```
# Построение базовой визуализации (столбиковая диаграмма)
### Данный вид диаграммы выбран: удобна для сравнения величин
```{r echo=FALSE, message = FALSE, warning=FALSE}
ggplot(data2, aes(x = data2$Продукт, y = data2$`Количество покупок`)) +
  geom_bar(stat="identity") +
  labs(title = "Распределение спроса на продукты питания", 
       y = "Количество покупок в %", x = "Название пиродукта") +
  theme_minimal() +
  scale_fill_brewer(palette="Pastel1") -> pr_1
pr_1
```


```{r echo=FALSE, message = FALSE, warning=FALSE}
ggplot(data2, aes(data2$Продукт, data2$`Количество покупок`)) + 
  geom_point() +
  geom_smooth(method="lm") +
  labs (
        x = "Название пиродукта",
        y = "Количество покупок в %") 
ggplot(data2, aes(data2$Продукт, data2$`Количество покупок`)) + 
  geom_point() +
  geom_smooth()+
  labs (
        x = "Название пиродукта",
        y = "Количество покупок в %") -> pr_2

```
# Размещение двух графиков
```{r echo=FALSE, message = FALSE, warning=FALSE}
library(gridExtra)
grid.arrange(pr_1, pr_2, ncol = 1, nrow = 2)

```




